### ISSUE TITLE
Google app launches extraneous Lynket instance

### ISSUE THREAD

**Issue by meraj-ahmed** [arunkumar9t2/lynket-browser#125]
Recently I've been seeing a strange issue when I launch links from the Google app (search results, Discover feed stories, etc.) using Lynket. The link opens just fine, but it also opens another instance of Lynket. This other instance appears blank in the running apps list, and when I tap on it, it switches to or relaunches the last opened link. I don't have a default browser set, I just select Lynket from the Open with dialog each time. It hasn't impacted any functionality, but it's just a small annoyance. Has anyone else observed this behavior?

![Screenshot_20190927-105951_One UI Home](https://user-images.githubusercontent.com/28062350/65784449-ae859c00-e117-11e9-9b9a-e0c9636ece05.jpg)

Lynket 2.1
Samsung GS9+
Android 9, OneUI

**Comment by arunkumar9t2** [comment]
Thanks for reporting. I will check this.

**Comment by AndreiZ88** [comment]
I'm also having this issue on a Samsung Note9 running Android Pie. This didn't happen until after updating to version 2.1.

**Comment by meraj-ahmed** [comment]
One additional detail about this issue. If I manually open Lynket and leave it open in the background, then opening links from the Google app does not launch the strange extraneous instance Lynket in this case. I don't know if this helps, but it seemed like it could be relevant.

**Comment by arunkumar9t2** [comment]
@meraj-ahmed, thanks for the updates. I will look into this shortly, I think I have an idea what's causing this.

**Comment by azumukupoe** [comment]
It's not only the Google app, probably any app.

**Comment by meraj-ahmed** [comment]
@azumukupoe at this point I have only seen it happen with the Google app, but I'm sure it may be possible with other apps that I do not have on my device.

**Comment by azumukupoe** [comment]
> 
> 
> @azumukupoe at this point I have only seen it happen with the Google app, but I'm sure it may be possible with other apps that I do not have on my device.

Okay I checked now and it didn't happen with Gmail.

**Comment by joshcangit** [comment]
I've started having this problem after Lynket's `2.1` major update. This Issue #125 should be renamed because it doesn't matter where or which app Lynket open a link from. This single extraneous Lynket instance appears most likely due to activating **Merge tabs and apps** under **Browsing options**. This annoying thing is a blank instance that redirects to the most recently opened Lynket tab or reopens that tab if that tab was closed. It also reappears when opening a new tab in Lynket if this single extraneous Lynket instance is not already present.

**Comment by meraj-ahmed** [comment]
@joshcangit, that's interesting that it's happening with any app for you but only with the Google app for me. I wonder what would account for that difference.

And you may be right about this issue being related to the *Merge tabs and apps* option. I was able to confirm that it does not occur when the option is disabled.

**Comment by joshcangit** [comment]
Yes, but if the *Merge tabs and apps* option is disabled, there'll be another problem where the tab management only shows 1 tab.

**Comment by joshcangit** [comment]
Turns out, that extraneous instance won't appear if Lynket itself is open, e.g., from app drawer, instead of just opening links. It will also get replaced if Lynket was opened.
So, maybe whenever a link is opened with Lynket, it tries to automatically open an instance of the app itself, alongside the latest instance with the webpage, which fails resulting in a blank extraneous instance.

**Comment by arunkumar9t2** [comment]
Hey all, thanks for all the discussion around this issue, I have identified the cause for it and have fixed it. It should be available for next update. As @meraj-ahmed noted, this can happen with any app when "Merge Tabs and Apps" are enabled, I am updating the title to reflect that.
