### ISSUE TITLE
Bottom color bug when incognito

### ISSUE THREAD

**Issue by azumukupoe** [arunkumar9t2/lynket-browser#62]
Default color for toolbar is used for bottom bar color instead of webpages' for some websites, which makes the bottons nearly visible when light color is set as default.

![Screenshot](https://i.imgur.com/slSTAfy.jpg)

**Comment by arunkumar9t2** [comment]
I am aware of this, thanks. 

This is due to lack of coloring API in the bottom bar library I am using. I need to migrate to other own which supports it or fork the existing one and make my changes. 

Since this is a lot of tech debt work, I am keeping this on low priority for now but will explore any hacky fixes before 2.0 release.

**Comment by azumukupoe** [comment]
Toolbar personalization not working correctly in incognito, using the default blue color.
